# This tasklist will do the actual initialization of a k8s cluster
---
- name: Create working directory
  ansible.builtin.tempfile:
    state: directory
  register: tempdir

- name: Parse working directory
  ansible.builtin.set_fact:
    tempdir: "{{ tempdir.path }}"

- name: Generate initial kubeadm config
  ansible.builtin.template:
    src: kubeadm-config.yaml.j2
    dest: "{{ tempdir }}/kubeadm-config.yaml"

- name: Initialize cluster
  ansible.builtin.command: "kubeadm init --config {{ tempdir }}/kubeadm-config.yaml"

- name: Init kube config
  ansible.builtin.file:
    path: /root/.kube
    state: directory

- name: Copy kubectl config
  ansible.builtin.command: "cp -f /etc/kubernetes/admin.conf /root/.kube/config"

- name: Cleanup
  ansible.builtin.file:
    path: "{{ tempdir }}"
    state: absent

- name: Deploy kube-router
  ansible.builtin.command: "kubectl apply -f https://raw.githubusercontent.com/cloudnativelabs/kube-router/master/daemonset/kubeadm-kuberouter.yaml"
