# Container runtime, right now only cri-o is supported
container_runtime: cri-o

# container runtime repo keyserver
container_runtime_signing_keyserver: keys.openpgp.org

# CRI cgroup driver
container_runtime_cgroup_driver: systemd

# container runtime - insecure registries
container_runtime_insecure_registries: []

# maximum container log size
container_runtime_max_log_size: 1000000

# Default sysctls for containers
container_runtime_default_sysctls: []

# Default environment for containers
container_runtime_default_environment: []

# CRI-O /etc/containers/registries.conf customization
#container_runtime_crio_containers_registries_conf:

# Enable default internal seccomp profile when profile is empty
# Sets crio.runtime.seccomp_use_default_when_empty
crio_runtime_seccomp_use_default_when_empty: False
