---
- name: Upgrade os
  apt:
    update_cache: yes
    upgrade: safe

- name: Cleanup apt
  command: apt-get clean

- name: Remove dangling initrd.img files
  shell: |-
    cd /boot
    set -- initrd.img-*
    test -f "$1" && \
    for i ; do
      v=${i#initrd.img-}
      test -f vmlinuz-${v} || rm $i
    done || :
    set -- uinitrd.img-*
    test -f "$1" && \
    for i ; do
      v=${i#uinitrd.img-}
      test -f vmlinuz-${v} || rm $i
    done || :
