---
- name: update apt cache
  apt: update_cache=Yes

- name: reload systemd
  systemd:
    daemon_reload: yes

- name: reexec systemd
  command: systemctl daemon-reexec

- name: restart docker
  service:
    name: docker
    state: restarted

- name: apply kubernetes sysctls
  command: sysctl -p /etc/sysctl.d/kubernetes-node.conf

- name: restart crio
  service:
    name: crio
    state: restarted
    enabled: yes
