---
- import_playbook: prepare.yml

- hosts: master
  become: true
  roles:
  - kubernetes/control-plane

- hosts: master
  serial: 1
  become: true
  roles:
  - kubernetes/node

- hosts: worker
  become: true
  roles:
  - kubernetes/node
