---
- import_playbook: prepare.yml

# Validate configuration, prepare kubernetes node
- hosts: cluster
  roles:
  - kubernetes/prepare
  - prepare/kubernetes-node

# Initialize k8s cluster if needed
- hosts: master
  roles:
  - kubernetes/control-plane

# Obtain one join command for playbook run
- hosts: cluster
  roles:
  - kubernetes/node-join-command

# join masters sequentially
- hosts: master
  serial: 1
  roles:
  - kubernetes/node

# join workers in parallel
- hosts: worker
  roles:
  - kubernetes/node
