---
- import_playbook: os.yml

- hosts: cluster
  roles:
  - prepare/container-runtime

- hosts: worker
  roles:
  - prepare/kubernetes-worker-node

- hosts: gluster
  roles:
  - prepare/gluster-node
