---
- import_playbook: os.yml

- hosts: cluster
  any_errors_fatal: true
  roles:
    - prepare/cri-o-version
    - prepare/container-runtime

- hosts: cluster,!master
  any_errors_fatal: true
  roles:
    - prepare/kubernetes-worker-node
