---
- hosts: cluster
  become: true
  roles:
  - os
  - prepare/kubernetes-node

- hosts: worker
  become: true
  roles:
  - prepare/kubernetes-worker-node

- hosts: gluster
  become: true
  roles:
  - prepare/gluster-node
