---
- name: Prepare reboots
  hosts: cluster
  roles:
  - kubernetes/choose-master
  - assign-ip
  - kubernetes/prepare-cni-check

- name: Reboot nodes
  gather_facts: false
  hosts: cluster
  serial: 1
  roles:
  - kubernetes/drain-node
  - kubernetes/stop-kubelet
  - reboot-node
  - kubernetes/check-apiserver
  - kubernetes/uncordon-node
