---
- hosts: cluster
  roles:
  - kubernetes/choose-master
  - assign-ip
  - kubernetes/prepare-cni-check

- hosts: master
  serial: 1
  roles:
  - kubernetes/reboot-node

- hosts: worker
  serial: "{{ REBOOT_SERIAL | default(1) }}"
  roles:
  - kubernetes/reboot-node
