---
- hosts: cluster
  gather_facts: false
  serial: 1
  tasks:
  - import_tasks: private/reboot-reboot.yml
  - import_tasks: private/check-apiserver.yml
  - import_tasks: private/reboot-uncordon.yml
