---
- hosts: cluster
  gather_facts: no
  become: yes
  any_errors_fatal: true
  tasks:
  - name: Upgrade kubeadm
    import_tasks: private/upgrade-kubeadm.yml

- hosts: master
  gather_facts: no
  become: yes
  any_errors_fatal: true
  roles:
  - kubernetes-control-plane

- hosts: master
  gather_facts: no
  become: yes
  any_errors_fatal: true
  tasks:
  - name: Upgrade control plane
    import_tasks: private/upgrade-master.yml

- hosts: worker
  serial: 1
  gather_facts: no
  become: yes
  any_errors_fatal: true
  tasks:
  - name: Upgrade worker node
    import_tasks: private/upgrade-worker.yml

- hosts: cluster
  gather_facts: no
  become: yes
  tasks:
  - name: Remove ds/kube-proxy
    import_tasks: private/upgrade-remove-kube-proxy-ds.yml
