---
- hosts: cluster
  gather_facts: no
  any_errors_fatal: true
  roles:
  - kubernetes/prepare
  - kubernetes/choose-master
  - kubernetes/prepare-cni-check
  - upgrade/kubeadm

# redeploy apiserver-loadbalancer
- hosts: master
  any_errors_fatal: true
  roles:
  - kubernetes/apiserver-loadbalancer/prepare

- hosts: master
  serial: 1
  gather_facts: no
  any_errors_fatal: true
  roles:
  - kubernetes/drain-node
  - kubernetes/apiserver-loadbalancer/deploy
  - upgrade/control-plane
  - upgrade/kubelet-kubectl
  - kubernetes/uncordon-node

- hosts: worker
  serial: 1
  gather_facts: no
  any_errors_fatal: true
  roles:
  - kubernetes/drain-node
  - upgrade/worker
  - upgrade/kubelet-kubectl
  - kubernetes/uncordon-node
