---
- hosts: cluster
  gather_facts: no
  any_errors_fatal: true
  roles:
  - kubernetes/prepare
  - prepare/kubernetes-repository
  - kubernetes/choose-master
  - kubernetes/prepare-cni-check
  - upgrade/kubeadm

- hosts: master,worker
  serial: 1
  gather_facts: no
  any_errors_fatal: true
  roles:
  - kubernetes/drain-node
  - upgrade/node
  - upgrade/kubelet-kubectl
  - kubernetes/uncordon-node
