---
- hosts: all
  gather_facts: no
  tasks:
  - name: Set supported kubernetes version
    set_fact:
      supported_kubernetes_version: [1, 15]
    run_once: yes

- hosts: cluster
  gather_facts: no
  become: yes
  any_errors_fatal: true
  roles:
  - upgrade/kubeadm

- hosts: master
  gather_facts: no
  become: yes
  any_errors_fatal: true
  roles:
  - kubernetes-control-plane

- hosts: master
  serial: 1
  gather_facts: no
  become: yes
  any_errors_fatal: true
  roles:
  - upgrade/control-plane
  - upgrade/kubelet-kubectl

- hosts: worker
  serial: 1
  gather_facts: no
  become: yes
  any_errors_fatal: true
  roles:
  - upgrade/worker
  - upgrade/kubelet-kubectl

- hosts: cluster
  gather_facts: no
  become: yes
  tasks:
  - name: Remove ds/kube-proxy
    import_tasks: private/upgrade-remove-kube-proxy-ds.yml
