---
- name: Prepare reboots
  hosts: cluster
  roles:
  - kubernetes/choose-master
  - assign-ip
  - kubernetes/prepare-cni-check

- name: "Upgrade & Reboot nodes"
  hosts: master,worker
  serial: 1
  roles:
  - kubernetes/drain-node
  - upgrade/os
  - kubernetes/reboot-node
  - kubernetes/uncordon-node
