---
- name: Prepare reboots
  hosts: cluster
  roles:
  - kubernetes/choose-master
  - assign-ip
  - prepare/cri-o-version
  - kubernetes/prepare-cni-check

- name: "Upgrade & Reboot nodes"
  hosts: master,worker
  serial: 1
  roles:
  - kubernetes/drain-node
  - kubernetes/stop-kubelet
  - upgrade/os
  - upgrade/container-runtime
  - reboot-node
  - kubernetes/check-apiserver
  - kubernetes/uncordon-node
