---
- name: Prepare for upgrade
  hosts: cluster
  gather_facts: false
  any_errors_fatal: true
  roles:
  - kubernetes/prepare
  - prepare/kubernetes-repository
  - kubernetes/choose-master
  - kubernetes/prepare-cni-check
  - upgrade/kubeadm

- name: Upgrade master kubernetes nodes
  hosts: master
  serial: 1
  gather_facts: false
  any_errors_fatal: true
  roles:
  - upgrade/node

- name: Upgrade non-master kubernetes nodes
  hosts: cluster,!master
  gather_facts: false
  any_errors_fatal: true
  roles:
  - upgrade/node

- name: Upgrade kubelet and kubectl on nodes
  hosts: cluster
  serial: 1
  gather_facts: false
  any_errors_fatal: true
  roles:
  - kubernetes/drain-node
  - upgrade/kubelet-kubectl
  - kubernetes/uncordon-node
