---
- name: "Fetch installed packages"
  package_facts: {}

- name: Remove docker and crio
  shell: 'apt-get remove --purge --autoremove --yes --allow-change-held-packages docker.* cri-o-.* conmon.* containers.* runc.*'
  ignore_errors: yes
  args:
    warn: False
  when: 'ansible_facts.packages["cri-o-" + cri_o_version] is not defined'
