---
- name: Check whether cri-o is installed
  shell: "dpkg -l | grep -qE '^ii[[:space:]]+cri-o-'"
  register: cri_o_installed
  ignore_errors: yes

- include_tasks: cri-o-setup.yml
  when: cri_o_installed.rc != 0
