---
- name: "Ensure CRI directories are absent"
  file:
    path: "{{ item }}"
    state: absent
  loop:
  - /var/lib/containers
  - /var/lib/docker
  - /var/lib/crio
  - /etc/crio
  - /etc/cni
  - /etc/apt/sources.list.d/cri-o.list

- name: Import apt.srv.kojedz.in signing key
  apt_key:
    keyserver: keys.openpgp.org
    id: 2ADADF37C3C302A7BADABCC10D946CE6DD9F32EB

- name: Deploy cri-o sources.list
  copy:
    content: "deb http://apt.srv.kojedz.in/ {{ ansible_distribution_release }} main"
    dest: /etc/apt/sources.list.d/cri-o.list
  notify: update apt cache

- meta: flush_handlers

- name: install cri-o
  apt:
    name:
    - cri-o-{{ cri_o_version }}
  notify: reload systemd

- meta: flush_handlers

- name: clear cri-o shipped cni configuration
  file:
    path: "/etc/cni/net.d/{{ item }}"
    state: absent
  loop: "{{ cri_o_cni_configurations }}"
  notify: restart crio

- name: Ensure crio is started
  service:
    name: crio
    enabled: yes
