---
sources:
- "deb http://cdn-fastly.deb.debian.org/debian/ {{ ansible_distribution_release }} main"
- "deb http://cdn-fastly.deb.debian.org/debian/ {{ ansible_distribution_release }}-updates main"
- |-
  deb http://cdn-fastly.deb.debian.org/debian-security/ {{ ansible_distribution_release }}
  {%- if ansible_distribution_release == "bullseye" -%}
    -security
  {%- else -%}
    /updates
  {%- endif %} main

essential_packages:
- less
- net-tools
- irqbalance

os_fw_modules:
- br-netfilter

watchdog_ssh_keyfile: /root/.ssh/watchdog_key
watchdog_ssh_comment: 'watchdog ssh key'
watchdog_ssh_known_hosts: /root/.ssh/known_hosts
watchdog_ssh_testscript: /usr/local/sbin/watchdogd_ssh_localhost
watchdog_interval: 10
