---
- name: Use existing chosen_master
  set_fact:
    chosen_master: "{{ hostvars[groups['master'] | first].chosen_master }}"
  run_once: yes

- name: Obtain join command
  run_once: yes
  delegate_to: "{{ chosen_master }}"
  command: "kubeadm token create --print-join-command"
  register: join_command

- name: Parse join command
  run_once: yes
  set_fact:
    join_command: "{{ join_command.stdout_lines[0] }}"
