# At this point we have all masters operational, so we can depend on the first
# master's variables, facts.
---
- name: Obtain join command
  run_once: yes
  delegate_to: "{{ groups['master'] | first }}"
  command: "kubeadm token create --print-join-command"
  register: join_command

- name: Parse join command
  run_once: yes
  set_fact:
    join_command: "{{ join_command.stdout_lines[0] }}"

- name: Check if node needs to be joined
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf_stat

- name: Join node to cluster
  when: not kubelet_conf_stat.stat.exists
  command: "{{ join_command }}"
