---
- name: Upgrade first master
  when: inventory_hostname == groups['master'][0]
  block:
  - name: Upgrade control plane
    command: kubeadm upgrade apply --yes v{{ kubernetes_version }}

  - name: Unhold kubectl/kubelet
    command: apt-mark unhold kubectl kubelet

  - name: Upgrade kubectl/kubelet
    apt:
      name: kubectl={{ kubernetes_version }}-00,kubelet={{ kubernetes_version }}-00

  - name: Hold kubectl/kubelet
    command: apt-mark hold kubectl kubelet

- name: Upgrade other masters
  when: inventory_hostname != groups['master'][0]
  block:
  - name: Upgrade control plane
    command: kubeadm upgrade node experimental-control-plane

  - name: Unhold kubectl/kubelet
    command: apt-mark unhold kubectl kubelet

  - name: Upgrade kubectl/kubelet
    apt:
      name: kubectl={{ kubernetes_version }}-00,kubelet={{ kubernetes_version }}-00

  - name: Hold kubectl/kubelet
    command: apt-mark hold kubectl kubelet
