---
- name: Upgrade first master
  when: inventory_hostname == groups['master'][0]
  block:
  - name: Upgrade control plane
    command: kubeadm upgrade apply --yes v{{ kubernetes_version }} {{ kubeadm_skip_phases }}

  - name: Update kubectl config
    command: "cp -af /etc/kubernetes/admin.conf /root/.kube/config"

- name: Upgrade other masters
  when: inventory_hostname != groups['master'][0]
  block:
  - name: Upgrade control plane
    command: kubeadm upgrade node phase control-plane

  - name: Update kubectl config
    command: "cp -af /etc/kubernetes/admin.conf /root/.kube/config"

