---
- name: slurp file
  run_once: yes
  delegate_to: "{{ source_host }}"
  ansible.builtin.slurp:
    src: "{{ item.path }}"
  register: file_contents

- name: distribute file
  ansible.builtin.copy:
    content: "{{ file_contents.content | b64decode }}"
    dest: "{{ item.path }}"
    mode: "{{ item.mode | default('0644') }}"

- name: cleanup variable
  ansible.builtin.set_fact:
    file_contents: ""
  run_once: yes
  delegate_to: localhost
