---
- name: Install ca-certificates
  apt:
    name: ca-certificates

- name: Remove legacy files
  file:
    path: "{{ item }}"
    state: absent
  loop:
  - /etc/apt/keyrings/kubernetes-archive-keyring.gpg
  - /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  - /etc/apt/sources.list.d/kubernetes.list

- name: Download the public signing key for the Kubernetes package repositories
  ansible.builtin.uri:
    url: "https://pkgs.k8s.io/core:/stable:/v{{ supported_kubernetes_version | join('.') }}/deb/Release.key"
    return_content: true
  register: kubernetes_public_signing_key_armored
  delegate_to: localhost
  run_once: true

# TODO: switch to deb822_repository
- name: Prepare key to be embedded in debian sources
  command:
    cmd: sed -e "s/^$/./" -e "s/^/ /"
    stdin: "{{ kubernetes_public_signing_key_armored.content }}"
  register: kubernetes_public_signing_key_embedded
  delegate_to: localhost
  run_once: true
  changed_when: false

# TODO: switch to deb822_repository
- name: Deploy Kubernetes sources
  copy:
    content: |
      Types: deb
      URIs: https://pkgs.k8s.io/core:/stable:/v{{ supported_kubernetes_version | join('.') }}/deb/
      Suites: /
      Signed-By:
      {{ kubernetes_public_signing_key_embedded.stdout }}
    dest: /etc/apt/sources.list.d/kubernetes.sources
  notify: update apt cache

- meta: flush_handlers
