---
- name: Create /etc/apt/keyrings
  file:
    path: /etc/apt/keyrings
    state: directory

- name: Remove legacy Google Cloud public signing key
  file:
    path: /etc/apt/keyrings/kubernetes-archive-keyring.gpg
    state: absent

- name: Download the public signing key for the Kubernetes package repositories
  ansible.builtin.uri:
    url: "https://pkgs.k8s.io/core:/stable:/v{{ supported_kubernetes_version | join('.') }}/deb/Release.key"
    return_content: true
  register: kubernetes_public_signing_key_armored
  delegate_to: localhost
  run_once: true

- name: Dearmor the public signing key for the Kubernetes package repositories
  command:
    cmd: gpg --dearmor
    stdin: "{{ kubernetes_public_signing_key_armored.content }}"
  register: kubernetes_public_signing_key_dearmored
  delegate_to: localhost
  run_once: true
  changed_when: false

- name: Deploy the public signing key for the Kubernetes package repositories
  copy:
    content: "{{ kubernetes_public_signing_key_dearmored.stdout }}"
    dest: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Register Kubernetes apt repository
  copy:
    content: |
      deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ supported_kubernetes_version | join('.') }}/deb/ /
    dest: /etc/apt/sources.list.d/kubernetes.list
  notify: update apt cache

- meta: flush_handlers
