---
- name: fail if 'apt' variable is defined (deprecated)
  ansible.builtin.fail:
    msg: "The 'apt' variable is no longer supported"
  when: apt is defined

- name: remove unsupported ext.sources.list file
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/ext.sources.list
    state: absent
  notify: update apt cache
