---
- name: install cpufrequtils
  apt:
    name: cpufrequtils

- name: setup cpufrequtils
  template:
    src: defaults-cpufrequtils.j2
    dest: /etc/default/cpufrequtils
  notify:
  - reload systemd
  - restart cpufrequtils

- name: clear obsolete cpufrequtils systemd service dropin directory
  file:
    path: /etc/systemd/system/cpufrequtils.service.d
    state: absent
