---
- name: Remove obsolete fstrim scripts
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
  - /etc/cron.daily/fstrim
  - /etc/cron.weekly/fstrim

- name: Enable fstrim timer
  when: os_fstrim is defined
  block:
  - ansible.builtin.file:
      path: /etc/systemd/system/fstrim.timer.d
      state: directory

  - ansible.builtin.template:
      src: fstrim-timer-d-timer-os.conf.j2
      dest: /etc/systemd/system/fstrim.timer.d/timer-os.conf
    notify:
    - reload systemd

  - ansible.builtin.meta: flush_handlers

  - ansible.builtin.systemd:
      name: fstrim.timer
      state: started
      enabled: yes

- name: Disable fstrim timer
  when: os_fstrim is not defined
  block:
  - ansible.builtin.file:
      path: /etc/systemd/system/fstrim.timer.d
      state: absent
    notify:
    - reload systemd

  - ansible.builtin.meta: flush_handlers

  - ansible.builtin.systemd:
      name: fstrim.timer
      state: stopped
      enabled: no
