---
- name: remove obsolete fstrim scripts
  file:
    path: "{{ item }}"
    state: absent
  loop:
  - /etc/cron.daily/fstrim
  - /etc/cron.weekly/fstrim

- name: enable fstrim timer
  when: os_fstrim is defined
  block:
  - file:
      path: /etc/systemd/system/fstrim.timer.d
      state: directory

  - template:
      src: fstrim-timer-d-timer-os.conf.j2
      dest: /etc/systemd/system/fstrim.timer.d/timer-os.conf
    notify:
    - reload systemd

  - meta: flush_handlers

  - systemd:
      name: fstrim.timer
      state: started
      enabled: yes

- name: disable fstrim timer
  when: os_fstrim is not defined
  block:
  - file:
      path: /etc/systemd/system/fstrim.timer.d
      state: absent
    notify:
    - reload systemd

  - meta: flush_handlers

  - systemd:
      name: fstrim.timer
      state: stopped
      enabled: no
