---
- fail:
    msg: "Only Debian is supported. Detected: {{ ansible_distribution }}"
  when: ansible_distribution != "Debian"

- name: Setup host ip
  when: ip is not defined
  set_fact:
    ip: "{{ ansible_default_ipv4.address }}"

- import_tasks: resolv.yml

- template:
    src: sources.list.j2
    dest: /etc/apt/sources.list
  notify: update apt cache
  tags:
  - sources-list

- import_tasks: apt-ext-lists.yml
  tags:
  - sources-list

- meta: flush_handlers

- name: install some essential packages
  apt:
    name: "{{ essential_packages }}"

- name: disable shell history
  file:
    path: /root/.bash_history
    state: link
    src: /dev/null
    force: yes

- import_tasks: modules.yml

- include_tasks: watchdog.yml
  when: os_setup_watchdog
  tags:
  - watchdog

- include_tasks: munin.yml
  when: os_setup_munin
  tags:
  - munin

- include_tasks: bind-services.yml
  when: os_bind_services

- include_tasks: cpufreq.yml
  when: os_setup_cpufreq
  tags:
  - cpufreq

- import_tasks: rsyslogd.yml
  tags:
  - syslog

- import_tasks: fstrim.yml
  tags:
  - fstrim
