---
- name: Check for supported OS
  fail:
    msg: "Only Debian is supported. Detected: {{ ansible_distribution }}"
  when: ansible_distribution != "Debian"

- import_tasks: checks.yml
  tags:
  - checks

- import_tasks: resolv.yml

- name: remove deprecated /etc/apt/sources.list
  ansible.builtin.file:
    path: /etc/apt/sources.list
    state: absent
  notify: update apt cache

- name: generate /etc/apt/sources.list.d/debian.sources
  ansible.builtin.template:
    src: debian.sources.j2
    dest: /etc/apt/sources.list.d/debian.sources
    mode: '0644'
    owner: root
    group: root
  notify: update apt cache

- import_tasks: apt-ext-lists.yml

- meta: flush_handlers

- name: install some essential packages
  apt:
    name: "{{ essential_packages }}"

- name: disable shell history
  file:
    path: /root/.bash_history
    state: link
    src: /dev/null
    force: yes

- import_tasks: modules.yml

- import_tasks: watchdog.yml
  when: os_setup_watchdog
  tags:
  - watchdog

- include_tasks: bind-services.yml
  when: os_bind_services

- import_tasks: cpufreq.yml
  when: os_setup_cpufreq
  tags:
  - cpufreq

- import_tasks: rsyslogd.yml
  tags:
  - syslog

- import_tasks: fstrim.yml
  tags:
  - fstrim
