---
- name: Check for supported OS
  ansible.builtin.fail:
    msg: "Only Debian is supported. Detected: {{ ansible_distribution }}"
  when: ansible_distribution != "Debian"

- ansible.builtin.import_tasks: checks.yml
  tags:
  - checks

- ansible.builtin.import_tasks: resolv.yml

- name: Remove deprecated /etc/apt/sources.list
  ansible.builtin.file:
    path: /etc/apt/sources.list
    state: absent
  notify: Update apt cache

- name: Generate /etc/apt/sources.list.d/debian.sources
  ansible.builtin.template:
    src: debian.sources.j2
    dest: /etc/apt/sources.list.d/debian.sources
    mode: '0644'
    owner: root
    group: root
  notify: Update apt cache

- ansible.builtin.import_tasks: apt-ext-lists.yml

- ansible.builtin.meta: flush_handlers

- name: Install some essential packages
  ansible.builtin.apt:
    name: "{{ essential_packages }}"

- name: Disable shell history
  ansible.builtin.file:
    path: /root/.bash_history
    state: link
    src: /dev/null
    force: yes

- ansible.builtin.import_tasks: modules.yml

- ansible.builtin.import_tasks: watchdog.yml
  when: os_setup_watchdog
  tags:
  - watchdog

- ansible.builtin.include_tasks: bind-services.yml
  when: os_bind_services

- ansible.builtin.import_tasks: cpufreq.yml
  when: os_setup_cpufreq
  tags:
  - cpufreq

- ansible.builtin.import_tasks: rsyslogd.yml
  tags:
  - syslog

- ansible.builtin.import_tasks: fstrim.yml
  tags:
  - fstrim
