---
- name: blacklist modules
  template:
    src: blacklist.conf.j2
    dest: /etc/modprobe.d/blacklist.conf

- name: load modules
  template:
    src: os-fw.conf.j2
    dest: /etc/modules-load.d/os-fw.conf
