---
- name: blacklist modules
  template:
    src: blacklist.conf.j2
    dest: /etc/modprobe.d/blacklist.conf

- name: generate boot-time modules-load
  template:
    src: os-fw.conf.j2
    dest: /etc/modules-load.d/os-fw.conf

- name: load modules
  modprobe:
    name: "{{ item }}"
  loop: "{{ os_fw_modules }}"
