---
- name: Install munin packages
  apt:
    name:
    - munin-node
    - bc

- lineinfile:
    dest: /etc/munin/munin-node.conf
    regexp: host_name
    line: "host_name {{ inventory_hostname }}"
  notify: restart munin-node

- lineinfile:
    dest: /etc/munin/munin-node.conf
    regexp: ^cidr_allow
    line: "cidr_allow {{ os_munin_cidr_allow }}"
  notify: restart munin-node
