---
- name: generate /etc/hostname
  ansible.builtin.copy:
    content: |
      {{ inventory_hostname }}
    dest: /etc/hostname
  notify:
  - hostname updated

- ansible.builtin.meta: flush_handlers

- name: generate hosts file
  ansible.builtin.template:
    src: hosts.j2
    dest: /etc/hosts

- name: generate resolv.conf
  ansible.builtin.template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
  when: dnsConfig is defined
