---
- name: Generate /etc/hostname
  ansible.builtin.copy:
    content: |
      {{ inventory_hostname }}
    dest: /etc/hostname
  notify:
  - hostname updated

- ansible.builtin.meta: flush_handlers

- name: Generate hosts file
  ansible.builtin.template:
    src: hosts.j2
    dest: /etc/hosts

- name: Generate resolv.conf
  ansible.builtin.template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
  when: dnsConfig is defined
