- name: Setup rsyslogd remote logging
  ansible.builtin.copy:
    content: |
      *.* @{{ rsyslogd_remote }}
    dest: /etc/rsyslog.d/zz-remotelog.conf
  notify: restart rsyslogd
  when: rsyslogd_remote is defined

- name: Clear rsyslogd remote logging
  ansible.builtin.file:
    path: /etc/rsyslog.d/zz-remotelog.conf
    state: absent
  notify: restart rsyslogd
  when: rsyslogd_remote is not defined
