---
- name: apply kubernetes sysctls
  ansible.builtin.command: sysctl -p /etc/sysctl.d/kubernetes-node.conf

- name: restart kubelet
  ansible.builtin.systemd:
    daemon_reload: yes
    name: kubelet
    state: restarted
