---
- name: Set supported kubernetes version
  set_fact:
    supported_kubernetes_version: [1, 26]
  run_once: yes

- name: Assign kubernetes_version based on supported kubernetes version
  set_fact:
    kubernetes_version: "{{ (supported_kubernetes_version + (0,)) | join('.') }}"
  run_once: yes
  when: kubernetes_version is not defined

- name: Parse desired kubernetes version string
  set_fact:
    desired_kubernetes_version: "{{ kubernetes_version.split('.') }}"
  run_once: yes

- name: Fail on unsupported desired kubernetes version
  fail:
    msg: "Only {{ supported_kubernetes_version }} is supported"
  run_once: yes
  when: 'desired_kubernetes_version[0]|int != supported_kubernetes_version[0] or desired_kubernetes_version[1]|int != supported_kubernetes_version[1]'
