---
os_setup_cpufreq: False
cpufreq:
  governor: ondemand

#rsyslogd_remote: 192.168.1.1

apt:
  ext:
    keyserver: ""
    key_ids: []
    sources: []

# Enable fstrim.service. Possible values: daily|weekly
#os_fstrim: weekly

# resolver configuration
#dnsConfig:
#  search:
#  - lan
#  - doma.in
#  nameservers:
#  - 8.8.8.8

# Setup watchdog daemon, with periodic ssh to itself, and reboot if fails.
# This can detect hangups, etc.
os_setup_watchdog: False

# Bind configured services to `ip`
os_bind_services: False
