---
- name: update apt cache
  ansible.builtin.apt: update_cache=Yes

- name: stop watchdogd
  ansible.builtin.service:
    name: watchdog
    state: stopped
  listen: restart watchdogd

- name: start watchdogd
  ansible.builtin.service:
    name: watchdog
    state: started
  listen: restart watchdogd

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: restart cpufrequtils
  ansible.builtin.service:
    name: cpufrequtils
    state: restarted

- name: restart rsyslogd
  ansible.builtin.service:
    name: rsyslog
    state: restarted

- name: set hostname
  listen: hostname updated
  ansible.builtin.command: hostname --file /etc/hostname
