---
- name: Update apt cache
  ansible.builtin.apt: update_cache=Yes

- name: Stop watchdogd
  ansible.builtin.service:
    name: watchdog
    state: stopped
  listen: restart watchdogd

- name: Start watchdogd
  ansible.builtin.service:
    name: watchdog
    state: started
  listen: restart watchdogd

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Restart cpufrequtils
  ansible.builtin.service:
    name: cpufrequtils
    state: restarted

- name: Restart rsyslogd
  ansible.builtin.service:
    name: rsyslog
    state: restarted

- name: Set hostname
  listen: hostname updated
  ansible.builtin.command: hostname --file /etc/hostname
