- name: Enable legacy iptables tools
  alternatives:
    name: "{{ item.name }}"
    path: "{{ item.path }}"
  loop:
  - name: iptables
    path: /usr/sbin/iptables-legacy
  - name: ip6tables
    path: /usr/sbin/ip6tables-legacy
  - name: ebtables
    path: /usr/sbin/ebtables-legacy
