---
- name: Pre-check
  run_once: yes
  delegate_to: localhost
  import_tasks: precheck.yml

- apt: name=curl,tcpdump

- name: Setup systemd default accounting
  replace:
    path: /etc/systemd/system.conf
    regexp: '^.*(DefaultCPUAccounting|DefaultMemoryAccounting|DefaultTasksAccounting).*'
    replace: '\1=yes'
  notify: reexec systemd

- meta: flush_handlers

- name: disable swap permanently
  lineinfile:
    dest: /etc/fstab
    regexp: swap
    state: absent

- name: disable active swap
  command: swapoff -a

- name: import google apt key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg

- name: deploy kubernetes sources.list
  copy:
    src: kubernetes.list
    dest: /etc/apt/sources.list.d/
  notify: update apt cache

- meta: flush_handlers

- name: install kubernetes packages
  apt:
    name:
    - "kubelet={{ kubernetes_version }}-00"
    - "kubeadm={{ kubernetes_version }}-00"
    - "kubectl={{ kubernetes_version }}-00"

- name: hold kubernetes packages
  shell: apt-mark hold kubelet kubeadm kubectl

- name: restart kubelet service
  systemd:
    daemon_reload: yes
    name: kubelet
    state: restarted

- name: deploy kubernetes sysctls
  template:
    src: kubernetes-node.conf.j2
    dest: /etc/sysctl.d/kubernetes-node.conf
  notify: apply kubernetes sysctls
  tags:
  - sysctl

- import_tasks: iptables-legacy.yml
  when: ansible_distribution_release == 'buster'

- name: Load modules for IPVS on boot
  template:
    src: ipvs-modules.conf.j2
    dest: /etc/modules-load.d/ipvs-modules.conf

- name: Load modules for IPVS
  shell: "modprobe {{ item }} || true"
  loop: "{{ kuberneter_node_ipvs_modules }}"
