---
- apt: name=curl,tcpdump

- name: disable swap permanently
  lineinfile:
    dest: /etc/fstab
    regexp: swap
    state: absent

- name: disable active swap
  command: swapoff -a

- name: install kubernetes packages
  apt:
    name:
    - "kubelet={{ kubernetes_version }}-1.1"
    - "kubeadm={{ kubernetes_version }}-1.1"
    - "kubectl={{ kubernetes_version }}-1.1"
  notify: restart kubelet

- name: hold kubernetes packages
  shell: apt-mark hold kubelet kubeadm kubectl

- name: deploy kubelet extra args
  template:
    src: default_kubelet.j2
    dest: /etc/default/kubelet
  notify: restart kubelet

- meta: flush_handlers

- name: deploy kubernetes sysctls
  template:
    src: kubernetes-node.conf.j2
    dest: /etc/sysctl.d/kubernetes-node.conf
  notify: apply kubernetes sysctls
  tags:
  - sysctl

- name: Load modules for IPVS on boot
  template:
    src: ipvs-modules.conf.j2
    dest: /etc/modules-load.d/ipvs-modules.conf

- name: Load modules for IPVS
  shell: "modprobe {{ item }} || true"
  loop: "{{ kuberneter_node_ipvs_modules }}"
