---
- name: Disable swap permanently
  ansible.builtin.lineinfile:
    dest: /etc/fstab
    regexp: swap
    state: absent

- name: Disable active swap
  ansible.builtin.command: swapoff -a

- name: Install kubernetes packages
  ansible.builtin.apt:
    name:
    - "kubelet={{ kubernetes_version }}-*"
    - "kubeadm={{ kubernetes_version }}-*"
    - "kubectl={{ kubernetes_version }}-*"
  notify: Restart kubelet

- name: Hold kubernetes packages
  ansible.builtin.shell: apt-mark hold kubelet kubeadm kubectl

- ansible.builtin.fail:
    msg: "Setting kubernetes_node_ip is deprecated, migrate to kubernetes_node_ipv4_address."
  when: kubernetes_node_ip is defined
  ignore_errors: True

- name: Set kubernetes_node_ips
  ansible.builtin.set_fact:
    kubernetes_node_ips: |-
      {%- set ns = namespace(ips=[]) %}
      {%- if kubernetes_node_ip is defined %}
        {%- set ns.ips = ns.ips + [kubernetes_node_ip] %}
      {%- elif kubernetes_node_ipv4_address %}
        {%- if kubernetes_node_ipv4_address in ansible_facts %}
          {%- set ns.ips = ns.ips + [ansible_facts[kubernetes_node_ipv4_address].ipv4.address] %}
        {%- else %}
          {%- set ns.ips = ns.ips + [kubernetes_node_ipv4_address] %}
        {%- endif %}
      {%- endif %}

      {%- if kubernetes_node_ipv6_address %}
        {%- if kubernetes_node_ipv6_address in ansible_facts %}
          {%- set ns.ips = ns.ips + [ansible_facts[kubernetes_node_ipv6_address].ipv6 | selectattr('scope', 'equalto', 'global') | map(attribute='address') | first] %}
        {%- else %}
          {%- set ns.ips = ns.ips + [kubernetes_node_ipv6_address] %}
        {%- endif %}
      {%- endif %}
      {{- ns.ips -}}

- name: Deploy kubelet extra args
  ansible.builtin.template:
    src: default_kubelet.j2
    dest: /etc/default/kubelet
  notify: Restart kubelet

- ansible.builtin.meta: flush_handlers

- name: Deploy kubernetes sysctls
  ansible.builtin.template:
    src: kubernetes-node.conf.j2
    dest: /etc/sysctl.d/kubernetes-node.conf
  notify: Apply kubernetes sysctls
  tags:
  - sysctl

- name: Load modules for IPVS on boot
  ansible.builtin.template:
    src: ipvs-modules.conf.j2
    dest: /etc/modules-load.d/ipvs-modules.conf

- name: Load modules for IPVS
  ansible.builtin.shell: "modprobe {{ item }} || true"
  loop: "{{ kuberneter_node_ipvs_modules }}"
