---
- name: "{{ inventory_hostname }} - wait until apiserver becomes healthy"
  when: "'master' in group_names"
  ansible.builtin.command:
    argv:
      - curl
      - --max-time
      - "1"
      - -s
      - --cacert
      - /etc/kubernetes/pki/ca.crt
      - "https://{{ ip }}:6443/healthz"
  register: result
  until: "'ok' == result.stdout"
  retries: 120
  delay: 5
  tags:
    - health-check
