---
# See roles/os/defaults/main.yml

# See roles/prepare/container-runtime/defaults/main.yml

# See roles/kubernetes/prepare/defaults/main.yml

# See roles/prepare/kubernetes-node/defaults/main.yml

# See roles/kubernetes/control-plane/defaults/main.yml
