---
- name: Unhold kubectl/kubelet
  ansible.builtin.command: apt-mark unhold kubectl kubelet

- name: Upgrade kubectl/kubelet
  ansible.builtin.apt:
    name:
    - "kubelet={{ kubernetes_version }}-*"
    - "kubectl={{ kubernetes_version }}-*"
  notify:
    - kubelet upgraded

- name: Hold kubectl/kubelet
  ansible.builtin.command: apt-mark hold kubectl kubelet

- name: Ensure kubelet is running
  ansible.builtin.systemd:
    name: kubelet
    state: started

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
