---
- name: Unhold kubectl/kubelet
  command: apt-mark unhold kubectl kubelet

- name: Upgrade kubectl/kubelet
  apt:
    name:
    - "kubelet={{ kubernetes_version }}-1.1"
    - "kubectl={{ kubernetes_version }}-1.1"

- name: Hold kubectl/kubelet
  command: apt-mark hold kubectl kubelet

- name: Ensure kubelet is running
  systemd:
    name: kubelet
    state: started
