---
- name: Unhold kubectl/kubelet
  command: apt-mark unhold kubectl kubelet

- name: Upgrade kubectl/kubelet
  apt:
    name:
    - "kubelet={{ kubernetes_version }}-*"
    - "kubectl={{ kubernetes_version }}-*"
  notify:
    - kubelet upgraded

- name: Hold kubectl/kubelet
  command: apt-mark hold kubectl kubelet

- name: Ensure kubelet is running
  systemd:
    name: kubelet
    state: started

- name: Flush handlers
  meta: flush_handlers
