# Drain a node
---
- name: Ensure node is Ready
  ansible.builtin.command:
    argv:
    - kubectl
    - get
    - node
    - "{{ inventory_hostname }}"
    - -o
    - jsonpath={range .status.conditions[?(.reason == "KubeletReady")]}{.reason}{"\n"}{end}
  delegate_to: "{{ chosen_master }}"
  register: node_status
  failed_when: "not node_status.stdout_lines"
  retries: 1

- name: "Drain node"
  command: "kubectl {% if kubernetes_drain_node_localhost_kubectl_context %}--context={{ kubernetes_drain_node_localhost_kubectl_context }}{% endif %} drain --ignore-daemonsets --delete-emptydir-data --force {{ inventory_hostname }}"
  delegate_to: "{{ 'localhost' if kubernetes_drain_node_localhost_kubectl_context else chosen_master }}"
  retries: 1
