# Drain a node
---
- name: "{{ inventory_hostname }} - check status"
  command:
  args:
    argv:
    - kubectl
    - get
    - node
    - "{{ inventory_hostname }}"
    - -o
    - jsonpath={range .status.conditions[:]}{.reason}{"\n"}{end}
  delegate_to: "{{ chosen_master }}"
  register: node_status

- fail:
    msg: "{{ inventory_hostname }} is NotReady"
  when: "'NodeStatusUnknown' in node_status.stdout_lines"

- name: "{{ inventory_hostname }} - drain"
  command: "kubectl drain --ignore-daemonsets --delete-local-data --force {{ inventory_hostname }}"
  delegate_to: "{{ chosen_master }}"
