# Drain a node
---
- name: Ensure node is Ready
  ansible.builtin.command:
    argv:
    - kubectl
    - get
    - node
    - "{{ inventory_hostname }}"
    - -o
    - jsonpath={range .status.conditions[?(.reason == "KubeletReady")]}{.reason}{"\n"}{end}
  delegate_to: "{{ chosen_master }}"
  register: node_status
  failed_when: "not node_status.stdout_lines"

- name: "Drain node"
  command: "kubectl drain --ignore-daemonsets --delete-emptydir-data --force {{ inventory_hostname }}"
  delegate_to: "{{ chosen_master }}"
  when: not kubernetes_drain_node_localhost_kubectl_context

- name: "Drain node from localhost"
  command: "kubectl --context={{ kubernetes_drain_node_localhost_kubectl_context }} drain --ignore-daemonsets --delete-emptydir-data --force {{ inventory_hostname }}"
  delegate_to: localhost
  when: kubernetes_drain_node_localhost_kubectl_context
  register: node_drain_from_localhost_result
  retries: 1
  until: node_drain_from_localhost_result.rc == 0
