---
- name: Import docker gpg key
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    keyserver: pool.sks-keyservers.net

- name: Deploy docker sources.list
  copy:
    content: "deb https://download.docker.com/linux/debian {{ os_debian_distribution }} stable"
    dest: /etc/apt/sources.list.d/docker.list
  notify: update apt cache

- meta: flush_handlers

- name: Install docker
  apt:
    name: docker-ce
  notify: reload systemd

- name: Configure docker
  template:
    src: docker-daemon.json.j2
    dest: /etc/docker/daemon.json
  notify: restart docker
